// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lziezwyafqusmtpcojwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6aWV6d3lhZnF1c210cGNvandvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzkyMjksImV4cCI6MjA2NjYxNTIyOX0.F5Lstbw1043d3jmlskbGsdQhiUMcJY5FNWcUUpDarG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);